//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnerGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicator
    {
        public int id { get; set; }
        public string customer { get; set; }
        public int value { get; set; }
        public string energy { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
    }
}
