//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnerGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Readout
    {
        public int id { get; set; }
        public string evaluatedCustomer { get; set; }
        public System.DateTime reviewDate { get; set; }
        public string value { get; set; }
        public string comment { get; set; }
    }
}
